#!/usr/bin/env python3
"""
把主仓库里的 PoL/（中文）和 PoLEn/（英文）同步到 GitHub Wiki 仓库。

做的事：
  1. 按文件名生成 Wiki 页面名（中文：第N章-标题；英文：Chapter-N-Title）
  2. 改写链接：指向本仓库 md 的链接 -> Wiki 页面链接；图片/其它文件 -> 绝对地址
  3. 自动生成 Home.md 和 _Sidebar.md
  4. 通过清单文件 .sync-manifest.json 清理“主仓库已删除”的页面，不碰手写页面

只依赖 Python 3 标准库。
用法见文件末尾 main() 的参数说明，或运行：python sync_wiki.py --help
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path
from urllib.parse import quote, unquote

# --------------------------------------------------------------------------
# 配置区：一般只需要改这里
# --------------------------------------------------------------------------
SOURCES = [
    # dir: 主仓库里的目录；lang: 语言标识；label: 侧边栏分组标题
    {"dir": "PoL", "lang": "zh", "label": "中文版"},
    {"dir": "PoLEn", "lang": "en", "label": "English"},
]

# Readme 这类没有章节号的页面，避免中英文重名
README_NAMES = {"zh": "Readme-中文", "en": "Readme-English"}

# 源文件里有些链接指向旧文件名（已不存在）。按“标题”做别名：旧标题 -> 现标题
TITLE_ALIASES = {
    "zh": {
        "治理共识：爱的证明": "AI和人类文明的治理：从恨2证明到爱2证明",
        "爱、恨、文明、野蛮、爱的证明、仇恨证明、富仇文明与富爱文明": "爱2、恨2、爱2证明、恨2证明、富爱文明",
    },
    "en": {},
}

# 源文件里引用了不存在的图片时的兜底：缺失路径 -> 实际存在的路径（相对主仓库根目录）
IMAGE_ALIASES = {
    "PoL/svg/pol2_zh.svg": "PoL/svg/pol_zh.svg",
}

HOME_INTRO = {
    "zh": "爱2证明（Proof of Love2, PoL2）完整理论。",
    "en": "Proof of Love2 (PoL2): the full theory.",
}

MARKER = "<!-- AUTO-GENERATED by sync_wiki.py — 请在主仓库修改源文件，不要在 Wiki 里直接编辑 -->"
MANIFEST = ".sync-manifest.json"

# --------------------------------------------------------------------------
# 工具函数
# --------------------------------------------------------------------------
NUM_RE = re.compile(r"^(\d+)\.\s*(.+)$")
_GH_ANNOT = os.environ.get("GITHUB_ACTIONS") == "true"
WARNINGS: list[str] = []


def warn(msg: str) -> None:
    WARNINGS.append(msg)
    print(f"::warning::{msg}" if _GH_ANNOT else f"[warn] {msg}")


def clean(s: str) -> str:
    """把标题变成适合做 Wiki 文件名的形式：空格 -> '-'，去掉不安全字符。"""
    s = re.sub(r'[\\/:*?"<>|#\[\]{}%^`,.;!]', " ", s)
    s = re.sub(r"\s+", "-", s.strip())
    return s.strip("-")


def norm_title(s: str) -> str:
    """用于按标题模糊匹配：去掉空白、标点，转小写。"""
    return re.sub(r"[\s\-_,.;:：，。；！!?？、·]+", "", s).lower()


def enc(page: str) -> str:
    return quote(page, safe="")


class Doc:
    def __init__(self, src: Path, rel_repo: str, lang: str, label: str):
        self.src = src                # 本地绝对路径
        self.rel_repo = rel_repo      # 相对仓库根，如 "PoL/0. 前言.md"
        self.lang = lang
        self.label = label
        d = rel_repo.split("/", 1)[1]  # 去掉顶层目录
        parts = Path(d).with_suffix("").parts
        stem = parts[-1]
        self.num: int | None = None
        self.title = stem
        m = NUM_RE.match(stem) if len(parts) == 1 else None
        if m:
            self.num = int(m.group(1))
            self.title = m.group(2).strip()
            t = clean(self.title)
            self.page = f"第{self.num}章-{t}" if lang == "zh" else f"Chapter-{self.num}-{t}"
            self.display = f"{self.num}. {self.title}"
        else:
            base = "-".join(clean(p) for p in parts)
            if len(parts) == 1 and stem.lower() == "readme":
                base = README_NAMES[lang]
            elif lang != "zh":
                base = "EN-" + base
            self.page = base
            self.display = " / ".join(parts) if len(parts) > 1 else stem
            if len(parts) == 1 and stem.lower() == "readme":
                self.display = "Readme"


# --------------------------------------------------------------------------
# 收集文档 & 建索引
# --------------------------------------------------------------------------
def collect(main: Path) -> list[Doc]:
    docs: list[Doc] = []
    for s in SOURCES:
        base = main / s["dir"]
        if not base.is_dir():
            warn(f"目录不存在：{s['dir']}")
            continue
        for p in sorted(base.rglob("*.md")):
            rel = p.relative_to(main).as_posix()
            docs.append(Doc(p, rel, s["lang"], s["label"]))
    names: dict[str, str] = {}
    for d in docs:
        if d.page in names:
            raise SystemExit(f"页面名冲突：{d.page} <- {names[d.page]} / {d.rel_repo}")
        names[d.page] = d.rel_repo
    return docs


class Resolver:
    def __init__(self, main: Path, docs: list[Doc], repo: str, branch: str):
        self.main, self.repo, self.branch = main, repo, branch
        self.by_path = {d.rel_repo: d for d in docs}
        self.by_title: dict[tuple[str, str], Doc] = {}
        for d in docs:
            self.by_title.setdefault((d.lang, norm_title(d.title)), d)
        self.blob_re = re.compile(
            r"https://github\.com/" + re.escape(repo) + r"/(?:blob|tree)/[^/]+/"
        )

    # 把 url 变成“相对仓库根的路径”，不是本仓库内容则返回 None
    def to_repo_path(self, url: str, cur: Doc) -> tuple[str, str] | None:
        url, _, frag = url.partition("#")
        if self.blob_re.match(url):
            path = unquote(self.blob_re.sub("", url, count=1))
        elif re.match(r"^[a-zA-Z][a-zA-Z0-9+.-]*:", url) or url.startswith(("//", "/")) or not url:
            return None
        else:
            path = os.path.normpath(os.path.join(os.path.dirname(cur.rel_repo), unquote(url)))
            path = path.replace(os.sep, "/")
        return path, frag

    def find_doc(self, path: str, cur: Doc) -> Doc | None:
        if path in self.by_path:
            return self.by_path[path]
        top = path.split("/", 1)[0]
        lang = next((s["lang"] for s in SOURCES if s["dir"] == top), cur.lang)
        stem = Path(path).with_suffix("").name
        m = NUM_RE.match(stem)
        title = (m.group(2) if m else stem).strip()
        t = TITLE_ALIASES.get(lang, {}).get(title, title)
        return self.by_title.get((lang, norm_title(t)))

    def raw_or_blob(self, path: str, image: bool) -> str:
        if image and path in IMAGE_ALIASES:
            warn(f"图片 {path} 不存在，已改用 {IMAGE_ALIASES[path]}（建议在源文件里修正引用）")
            path = IMAGE_ALIASES[path]
        exists = (self.main / path).exists()
        if not exists:
            warn(f"引用的文件不存在：{path}")
        q = quote(path, safe="/")
        if image:
            return f"https://raw.githubusercontent.com/{self.repo}/{self.branch}/{q}"
        kind = "tree" if (self.main / path).is_dir() else "blob"
        return f"https://github.com/{self.repo}/{kind}/{self.branch}/{q}"

    def rewrite(self, url: str, cur: Doc, image: bool = False) -> str:
        r = self.to_repo_path(url, cur)
        if r is None:
            return url
        path, frag = r
        suffix = f"#{frag}" if frag else ""
        if not image and path.lower().endswith(".md"):
            d = self.find_doc(path, cur)
            if d:
                return enc(d.page) + suffix
            warn(f"{cur.rel_repo}: 找不到链接目标 {path}，保留为仓库里的地址")
        return self.raw_or_blob(path, image) + suffix


# --------------------------------------------------------------------------
# 正文改写（跳过代码块）
# --------------------------------------------------------------------------
MD_LINK = re.compile(r'(!?)\[((?:[^\[\]]|\[[^\]]*\])*)\]\(\s*(<[^>]+>|[^)\s]+)((?:\s+"[^"]*")?)\s*\)')
HTML_ATTR = re.compile(r'(<(?:img|a)\b[^>]*?\b(?:src|href)=)(["\'])(.*?)\2', re.I)
# 只处理真正的“引用式链接定义”：目标必须是 URL 或带扩展名的路径。
# 像 "[1]: 王德峰, [标题](url)" 这种脚注式文字不算，避免误改。
REF_DEF = re.compile(
    r"^(\s{0,3}\[(?!\^)[^\]]+\]:\s*)(https?://\S+|[^\s,\[\]]+\.(?:md|svg|png|jpe?g|gif|pdf))\s*$",
    re.M,
)
BARE_URL = re.compile(r"(?<![(\"'<])(https://github\.com/[^\s)>\"'\]]+)")


def transform(text: str, doc: Doc, res: Resolver) -> str:
    out: list[str] = []
    buf: list[str] = []
    fence: str | None = None

    def flush() -> None:
        if not buf:
            return
        chunk = "".join(buf)
        buf.clear()

        def md(m: re.Match) -> str:
            bang, label, url, title = m.groups()
            u = url[1:-1] if url.startswith("<") else url
            new = res.rewrite(u, doc, image=bool(bang))
            return f"{bang}[{label}]({new}{title})"

        def html(m: re.Match) -> str:
            head, q, url = m.groups()
            is_img = "img" in head.lower().split()[0]
            return f"{head}{q}{res.rewrite(url, doc, image=is_img)}{q}"

        chunk = MD_LINK.sub(md, chunk)
        chunk = HTML_ATTR.sub(html, chunk)
        chunk = REF_DEF.sub(lambda m: m.group(1) + res.rewrite(m.group(2), doc), chunk)

        def bare(m: re.Match) -> str:
            u = m.group(1).rstrip(".,;，。；")
            tail = m.group(1)[len(u):]
            if res.blob_re.match(u) and u.lower().endswith(".md"):
                return res.rewrite(u, doc) + tail
            return m.group(1)

        chunk = BARE_URL.sub(bare, chunk)
        out.append(chunk)

    for line in text.splitlines(keepends=True):
        s = line.lstrip()
        if fence is None and (s.startswith("```") or s.startswith("~~~")):
            flush()
            fence = s[:3]
            out.append(line)
        elif fence is not None:
            out.append(line)
            if s.startswith(fence):
                fence = None
        else:
            buf.append(line)
    flush()
    return "".join(out)


def footer(doc: Doc, repo: str, branch: str) -> str:
    url = f"https://github.com/{repo}/blob/{branch}/{quote(doc.rel_repo, safe='/')}"
    if doc.lang == "zh":
        return f"\n\n---\n<sub>本页自动同步自主仓库 [`{doc.rel_repo}`]({url})。请在主仓库修改，Wiki 上的直接编辑会被覆盖。</sub>\n"
    return f"\n\n---\n<sub>Synced automatically from [`{doc.rel_repo}`]({url}). Please edit the source in the main repository; edits made here will be overwritten.</sub>\n"


# --------------------------------------------------------------------------
# Home / Sidebar
# --------------------------------------------------------------------------
def sort_key(d: Doc):
    return (0, d.num, d.page) if d.num is not None else (1, 0, d.page)


def build_nav(docs: list[Doc], with_intro: bool) -> str:
    lines: list[str] = []
    for s in SOURCES:
        group = sorted((d for d in docs if d.lang == s["lang"]), key=sort_key)
        if not group:
            continue
        chapters = [d for d in group if d.num is not None]
        extras = [d for d in group if d.num is None]
        lines.append(f"### {s['label']}")
        if with_intro:
            lines.append(HOME_INTRO[s["lang"]])
            lines.append("")
        for d in chapters:
            lines.append(f"- [{d.display}]({enc(d.page)})")
        if extras:
            lines.append("- " + ("附录" if s["lang"] == "zh" else "Appendix"))
            for d in extras:
                lines.append(f"  - [{d.display}]({enc(d.page)})")
        lines.append("")
    return "\n".join(lines)


def build_home(docs: list[Doc]) -> str:
    return (
        f"{MARKER}\n# NaturalDAO Wiki\n\n"
        "本 Wiki 的内容由主仓库的 `PoL/`（中文）与 `PoLEn/`（English）自动同步。\n"
        "This wiki is synced automatically from `PoL/` (Chinese) and `PoLEn/` (English) in the main repository.\n\n"
        + build_nav(docs, with_intro=True)
    )


def build_sidebar(docs: list[Doc]) -> str:
    return f"{MARKER}\n**[Home](Home)**\n\n" + build_nav(docs, with_intro=False)


# --------------------------------------------------------------------------
# 主流程
# --------------------------------------------------------------------------
def write_if_changed(path: Path, content: str) -> bool:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8", newline="\n")
    return True


def main() -> int:
    ap = argparse.ArgumentParser(description="Sync PoL / PoLEn markdown to the GitHub Wiki repo")
    ap.add_argument("--main", default=".", help="主仓库根目录（默认当前目录）")
    ap.add_argument("--wiki", required=True, help="已 clone 的 wiki 仓库目录")
    ap.add_argument("--repo", default=os.environ.get("GITHUB_REPOSITORY", "naturaldao/NaturalDAO"))
    ap.add_argument("--branch", default="main", help="主仓库默认分支（用于图片/原文链接）")
    ap.add_argument("--no-footer", action="store_true", help="页面末尾不加“自动同步自…”说明")
    ap.add_argument("--dry-run", action="store_true", help="只报告，不写文件")
    a = ap.parse_args()

    main_dir, wiki = Path(a.main).resolve(), Path(a.wiki).resolve()
    if not wiki.is_dir():
        raise SystemExit(f"wiki 目录不存在：{wiki}")

    docs = collect(main_dir)
    if not docs:
        raise SystemExit("没有找到任何 markdown 源文件，已中止（避免误清空 wiki）")
    res = Resolver(main_dir, docs, a.repo, a.branch)

    desired: dict[str, str] = {}
    for d in docs:
        body = transform(d.src.read_text(encoding="utf-8"), d, res).rstrip("\n") + "\n"
        if not a.no_footer:
            body += footer(d, a.repo, a.branch)
        desired[f"{d.page}.md"] = f"{MARKER}\n\n{body}"
    desired["Home.md"] = build_home(docs)
    desired["_Sidebar.md"] = build_sidebar(docs)

    manifest_path = wiki / MANIFEST
    old = set()
    if manifest_path.exists():
        old = set(json.loads(manifest_path.read_text(encoding="utf-8")).get("files", []))

    changed, removed = [], []
    for name, content in desired.items():
        p = wiki / name
        if a.dry_run:
            if not p.exists() or p.read_text(encoding="utf-8") != content:
                changed.append(name)
        elif write_if_changed(p, content):
            changed.append(name)
    for name in sorted(old - set(desired)):
        p = wiki / name
        if p.exists():
            removed.append(name)
            if not a.dry_run:
                p.unlink()
    if not a.dry_run:
        write_if_changed(
            manifest_path,
            json.dumps({"files": sorted(desired)}, ensure_ascii=False, indent=2) + "\n",
        )

    print(f"页面总数 {len(desired)}；更新 {len(changed)}；删除 {len(removed)}；警告 {len(WARNINGS)}")
    for n in changed:
        print("  ~", n)
    for n in removed:
        print("  -", n)
    return 0


if __name__ == "__main__":
    sys.exit(main())
