"""Pool the evidence of the search runs of 1, 4 and 8 October 2026 into one corpus and write paper/counts_all.tex.

The paper reports one search completed on 8 October 2026. The records retrieved on 8 October were coded with the
same codebook and are kept in their own files (data/*_update_2026-10-08.csv); this script pools them with the
records of 1 and 4 October (data/evidence_coding.csv etc.) and computes every count the paper prints.
Run: python scripts/merge_all.py   (prints the per-requirement tallies and comparator breakdowns as well)
"""
import csv
import random
from collections import Counter
from pathlib import Path

R = Path(__file__).resolve().parent.parent
D = R / "data"
AXES = ["G1", "G2", "G3", "G4", "G5", "G6", "G7"]
EXCLUDED_DURING_CODING = {"zen23187206"}  # evaluates no typed decision model


def rows(name):
    with (D / name).open(encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def kappa(pairs):
    n = len(pairs)
    po = sum(a == b for a, b in pairs) / n
    ca, cb = Counter(a for a, _ in pairs), Counter(b for _, b in pairs)
    pe = sum(ca[k] * cb[k] for k in set(ca) | set(cb)) / n / n
    return (po - pe) / (1 - pe)


def main():
    main_rows = [r for r in rows("evidence_coding.csv") if r["in_tally"] == "yes"]
    upd_rows = [r for r in rows("evidence_coding_update_2026-10-08.csv") if r["in_tally"] == "yes"]
    pairs = main_rows + upd_rows
    codes = Counter(r["code"] for r in pairs)
    strong = Counter(r["code"] for r in pairs if r["quality"] == "stronger")
    nozen = Counter(r["code"] for r in pairs if r["source"] != "zenodo")
    coded_docs = {r["doc"] for r in pairs}

    # corpus: studies after full-text screening (main window counts.tex + retained 8 October records)
    qa_main = [r for r in rows("quality_appraisal.csv") if not r["excluded_reason"]]
    qa_upd = [r for r in rows("quality_appraisal_update_2026-10-08.csv") if r["doc"] not in EXCLUDED_DURING_CODING]
    upd_src = Counter("zenodo" if r["doc"].startswith("zen") else "arxiv" for r in qa_upd)
    n_arxiv, n_zenodo, n_alpha, n_grey = 79 + upd_src["arxiv"], 27 + upd_src["zenodo"], 1, 7
    n_studies = n_arxiv + n_zenodo + n_alpha
    qual = Counter(r["quality"] for r in qa_main + qa_upd)

    # blind second coding: random sample of the 1/4 October pairs and all 8 October pairs
    ag = [(r["first"], r["second"]) for r in rows("coder_agreement.csv") if r["status"] == "compared"]
    ag += [(r["first"], r["second"]) for r in rows("coder_agreement_update_2026-10-08.csv")]
    k = kappa(ag)
    rnd = random.Random(20261008)
    boots = sorted(kappa([rnd.choice(ag) for _ in ag]) for _ in range(4000))
    lo, hi = boots[int(0.025 * len(boots))], boots[int(0.975 * len(boots)) - 1]
    agree = sum(a == b for a, b in ag)

    comp = Counter(r["comparator"] for r in pairs)
    neg_comp = Counter(r["comparator"] for r in pairs if r["code"] == "N")
    n_compared = sum(v for c, v in comp.items() if c != "none")

    out = {
        "nArxivAll": n_arxiv, "nZenodoAll": n_zenodo, "nStudies": n_studies, "nGreyAll": n_grey,
        "nCodedAll": len(coded_docs), "nRowsAll": len(pairs),
        "nSAll": codes["S"], "nQAll": codes["Q"], "nNAll": codes["N"],
        "nStrongRowsAll": sum(strong.values()), "nStrongSAll": strong["S"], "nStrongQAll": strong["Q"], "nStrongNAll": strong["N"],
        "nNoZenRowsAll": sum(nozen.values()), "nNoZenSAll": nozen["S"], "nNoZenQAll": nozen["Q"], "nNoZenNAll": nozen["N"],
        "nAppraisedAll": len(qa_main) + len(qa_upd), "nStrongerAll": qual["stronger"], "nModerateAll": qual["moderate"], "nWeakerAll": qual["weaker"],
        "nKappaNAll": len(ag), "nKappaAgreeAll": f"{agree} of {len(ag)}", "nKappaAll": f"{k:.2f}",
        "nKappaAllLo": f"{lo:.2f}", "nKappaAllHi": f"{hi:.2f}",
        "nComparedAll": n_compared, "nCompBetter": comp["better"], "nCompSimilar": comp["similar"],
        "nCompMixed": comp["mixed"], "nCompWorse": comp["worse"],
        "nNegAll": codes["N"], "nNegNoComp": neg_comp["none"], "nNegComp": codes["N"] - neg_comp["none"],
        "nNegCompWorse": neg_comp["worse"], "nNegCompSimilar": neg_comp["similar"],
        "nNegCompMixed": neg_comp["mixed"], "nNegCompBetter": neg_comp["better"],
    }
    lines = ["% Generated by scripts/merge_all.py (all search runs pooled, to 8 October 2026); do not edit by hand."]
    lines += [f"\\newcommand{{\\{k}}}{{{v}}}" for k, v in out.items()]
    (R / "paper" / "counts_all.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")
    for k_, v in out.items():
        print(f"{k_:>18} {v}")
    print("\nper requirement: S/Q/N | comparator better/similar/mixed/worse/none")
    for a in AXES:
        ra = [r for r in pairs if r["axis"] == a]
        c = Counter(r["code"] for r in ra)
        cp = Counter(r["comparator"] for r in ra)
        print(f"{a}: S {c['S']}, Q {c['Q']}, N {c['N']} | {cp['better']}/{cp['similar']}/{cp['mixed']}/{cp['worse']}/{cp['none']}")
    print("\nstrong share", {x: round(100 * strong[x] / sum(strong.values())) for x in "SQN"},
          "all share", {x: round(100 * codes[x] / len(pairs)) for x in "SQN"},
          "no-zenodo share", {x: round(100 * nozen[x] / sum(nozen.values())) for x in "SQN"})
    zen = Counter(r["code"] for r in pairs if r["source"] == "zenodo")
    arx = Counter(r["code"] for r in pairs if r["source"] == "arxiv")
    print("zenodo N", zen["N"], "of", sum(zen.values()), "| arxiv N", arx["N"], "of", sum(arx.values()))


if __name__ == "__main__":
    main()
