"""Build the paper and its supplement, with cross-references in both directions.

The paper (main.tex) and the supplementary material (supplement.tex) are separate PDFs. Each imports the
other's labels from a generated file (supplement_labels.tex, main_labels.tex) so that \\cref works across
them; hyperlink targets are dropped, because they live in the other PDF.
Run:  python paper/build.py        (English, pdflatex)
      python paper/build.py --zh   (Chinese, xelatex, in paper/zh/)
"""
import re
import subprocess
import sys
from pathlib import Path

P = Path(__file__).resolve().parent


def groups(s, i):
    """Parse consecutive {...} groups starting at s[i]; return list of contents and end index."""
    out = []
    while i < len(s) and s[i] == "{":
        depth, j = 0, i
        while True:
            if s[j] == "{":
                depth += 1
            elif s[j] == "}":
                depth -= 1
                if depth == 0:
                    break
            j += 1
        out.append(s[i + 1:j])
        i = j + 1
    return out, i


def export_labels(aux, out):
    """Copy \\newlabel entries from an .aux file, with hyperref anchors removed."""
    text = aux.read_text(encoding="utf-8", errors="replace") if aux.exists() else ""
    lines = []
    for m in re.finditer(r"\\newlabel\{([^}]*)\}", text):
        name = m.group(1)
        g, _ = groups(text, m.end())
        if not g:
            continue
        inner, _ = groups(g[0], 0)
        if name.endswith("@cref") or len(inner) < 4:
            lines.append(f"\\newlabel{{{name}}}{{{g[0]}}}")
        else:
            inner[3] = ""  # hyperref anchor: the target is in the other PDF
            lines.append(f"\\newlabel{{{name}}}{{" + "".join("{" + x + "}" for x in inner) + "}")
    out.write_text("% Generated by build.py; do not edit.\n\\makeatletter\n" + "\n".join(lines)
                   + "\n\\makeatother\n", encoding="utf-8")
    return len(lines)


def run(cmd, cwd):
    subprocess.run(cmd, cwd=cwd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def main():
    zh = "--zh" in sys.argv
    d = P / "zh" if zh else P
    eng = "xelatex" if zh else "pdflatex"
    main_tex, supp_tex = ("main_zh", "supplement_zh") if zh else ("main", "supplement")
    for stem in (main_tex, supp_tex):
        for ext in (".aux", ".out", ".bbl"):
            (d / (stem + ext)).unlink(missing_ok=True)
    tex = [eng, "-interaction=nonstopmode"]
    for stem in (main_tex, supp_tex):
        run(tex + [stem], d)
        run(["bibtex", stem], d)
    for _ in range(3):
        n1 = export_labels(d / f"{supp_tex}.aux", d / "supplement_labels.tex")
        n2 = export_labels(d / f"{main_tex}.aux", d / "main_labels.tex")
        for stem in (main_tex, supp_tex):
            run(tex + [stem], d)
    for stem in (main_tex, supp_tex):
        log = (d / f"{stem}.log").read_text(encoding="latin-1")
        pages = re.search(r"Output written on \S+ \((\d+) pages", log)
        errs = log.count("\n!")
        undef = len(re.findall(r"(Citation|Reference) .* undefined", log))
        print(f"{stem}: {pages.group(1) if pages else '?'} pages, errors={errs}, undefined={undef}")
    print(f"labels: {n1} from supplement, {n2} from paper")


if __name__ == "__main__":
    main()
