"""Generate paper/corpus_update.bib for the sources of the 8 October 2026 update search.

Keys follow corpus.bib: arXiv 2610.02267 -> arx02267, Zenodo record 23075657 -> zen23075657.
Metadata comes from the arXiv abstract page (citation_* meta tags; the API was rate-limiting) and the
Zenodo records API. Sources: data/quality_appraisal_update_2026-10-08.csv (every document read in full).
Run: python paper/gen_update_bib.py
"""
import csv
import html
import json
import re
import time
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = Path(__file__).resolve().parent / "corpus_update.bib"
UA = {"User-Agent": "Mozilla/5.0 (PoL2-Jev-survey update bib)"}


def get(url):
    for attempt in range(5):
        try:
            with urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=60) as r:
                return r.read().decode("utf-8")
        except Exception:
            if attempt == 4:
                raise
            time.sleep(15 * (attempt + 1))


def tex(s):
    s = " ".join(s.split())
    for a, b in (("\\", ""), ("&", r"\&"), ("%", r"\%"), ("_", r"\_"), ("#", r"\#"), ("$", r"\$")):
        s = s.replace(a, b)
    return re.sub(r'"([^"]*)"', r"``\1''", s)


def arxiv_entry(key, aid):
    page = get(f"https://arxiv.org/abs/{aid}")
    meta = lambda k: [html.unescape(m) for m in re.findall(rf'<meta name="{k}" content="([^"]*)"', page)]
    authors = " and ".join(" ".join(reversed([p.strip() for p in a.split(",", 1)])) for a in meta("citation_author"))
    hist = re.findall(r"\[v(\d+)\]</strong>.*?(\w{3}, \d{1,2} \w{3} \d{4})", page, re.S)
    v1 = time.strftime("%Y-%m-%d", time.strptime(hist[0][1], "%a, %d %b %Y")) if hist else meta("citation_date")[0].replace("/", "-")
    latest = hist[-1][0] if hist else "1"
    cls = re.search(r'primary-subject">[^(]*\(([^)]+)\)', page)
    return (f"@misc{{{key},\n  title = {{{{{tex(meta('citation_title')[0])}}}}},\n  author = {{{tex(authors)}}},\n"
            f"  year = {{2026}},\n  eprint = {{{aid}}},\n  archivePrefix = {{arXiv}},\n"
            f"  primaryClass = {{{cls.group(1) if cls else 'cs.CL'}}},\n"
            f"  note = {{arXiv:{aid}v{latest}, first submitted {v1}; update search of 2026-10-08}},\n"
            f"  url = {{https://arxiv.org/abs/{aid}v{latest}}}\n}}")


def zenodo_entry(key, rid):
    md = json.loads(get(f"https://zenodo.org/api/records/{rid}"))["metadata"]
    authors = " and ".join(tex(c["name"] if "," not in c["name"] else " ".join(reversed([p.strip() for p in c["name"].split(",", 1)])))
                           for c in md.get("creators", []))
    kind = md.get("resource_type", {}).get("title", "record")
    return (f"@misc{{{key},\n  title = {{{{{tex(md['title'])}}}}},\n  author = {{{authors}}},\n  year = {{2026}},\n"
            f"  howpublished = {{Zenodo {kind.lower()}, {md.get('publication_date', '')}}},\n"
            f"  note = {{update search of 2026-10-08}},\n"
            f"  doi = {{10.5281/zenodo.{rid}}},\n  url = {{https://doi.org/10.5281/zenodo.{rid}}}\n}}")


def main():
    docs = [r["doc"] for r in csv.DictReader((ROOT / "data" / "quality_appraisal_update_2026-10-08.csv").open(encoding="utf-8"))]
    entries = []
    for d in sorted(docs):
        if d.startswith("arx"):
            entries.append(arxiv_entry(d, "2610." + d[3:]))
        else:
            entries.append(zenodo_entry(d, d[3:]))
        time.sleep(4)
        print(d)
    OUT.write_text("% Generated by paper/gen_update_bib.py; do not edit by hand.\n\n" + "\n\n".join(entries) + "\n", encoding="utf-8")
    print(len(entries), "entries ->", OUT.name)


if __name__ == "__main__":
    main()
