"""Generate sections/B_evidence.tex (Appendix B) from data/evidence_coding.csv.

One row per coded study x requirement pair that enters the tallies; the rationale with locators is in the CSV.
Run: python paper/gen_evidence_table.py
"""
import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = Path(__file__).resolve().parent / "sections" / "B_evidence.tex"
SYSTEM = {"hosted": "H", "open": "O", "both": "H+O", "hosted+open": "H+O", "none": "--"}
COMP = {"better": "better", "similar": "similar", "worse": "worse", "mixed": "mixed", "none": "--"}
MARK = {"zenodo": r"\zmark{}", "grey": r"\gmark{}"}


def main():
    rows = list(csv.DictReader((ROOT / "data" / "evidence_coding.csv").open(encoding="utf-8")))
    tallied = [r for r in rows if r["in_tally"] == "yes"]
    other = sorted({r["doc"] for r in rows if r["in_tally"] != "yes"} - {r["doc"] for r in tallied})
    order = {"S": 0, "Q": 1, "N": 2}
    tallied.sort(key=lambda r: (r["axis"], order[r["code"]], r["doc"]))
    head = r"\toprule Req. & Study & Code & vs.\ generative & System & Design \\ \midrule"
    lines = [
        "% Generated by gen_evidence_table.py from data/evidence_coding.csv; do not edit by hand.",
        r"\section{Evidence table}",
        r"\label{app:evidence}",
        "",
        r"\Cref{tab:evidence} lists every coded study--requirement pair that enters the tallies of \cref{fig:framework}. "
        r"\emph{Code}: S supports, Q qualifies, N negative, for detector use (\cref{app:codebook}). "
        r"\emph{vs.\ generative}: the typed model's result relative to a generative comparator on that requirement, where one was run. "
        r"\emph{System}: H hosted \jev{}, O open typed model only, H+O both. "
        r"\emph{Design}: design rating of \cref{sec:appraisal}. "
        r"The one-sentence rationale with locators for each row is in \texttt{data/evidence\_coding.csv}. "
        r"Read in full but not tallied, because they are non-empirical, measure no typed model or were reclassified as context: "
        + ", ".join(r"\cite{" + d + "}" for d in other) + ".",
        "",
        r"\begingroup\footnotesize",
        r"\renewcommand{\arraystretch}{1.1}",
        r"\begin{longtable}{@{}p{0.07\linewidth}p{0.30\linewidth}p{0.07\linewidth}p{0.17\linewidth}p{0.09\linewidth}p{0.12\linewidth}@{}}",
        r"\caption{Coded evidence by requirement.}\label{tab:evidence}\\",
        head + r" \endfirsthead",
        head + r" \endhead",
        r"\bottomrule \endfoot",
    ]
    for r in tallied:
        lines.append(f"{r['axis']} & \\cite{{{r['doc']}}}{MARK.get(r['source'], '')} & {r['code']} & "
                     f"{COMP.get(r['comparator'], r['comparator'])} & {SYSTEM.get(r['system'], r['system'])} & {r['quality']} \\\\")
    lines += [r"\end{longtable}", ""]

    # update search of 2026-10-08: reported separately, not part of the main tallies
    upd = [r for r in csv.DictReader((ROOT / "data" / "evidence_coding_update_2026-10-08.csv").open(encoding="utf-8"))
           if r["in_tally"] == "yes"]
    upd.sort(key=lambda r: (r["axis"], order[r["code"]], r["doc"]))
    setmark = {"post-window": "P", "late-indexed": "L", "re-screened": "R"}
    uhead = r"\toprule Req. & Study & Set & Code & vs.\ generative & System & Design \\ \midrule"
    lines += [
        r"\Cref{tab:evidence-update} lists the pairs coded in the update search of 8~October (\cref{sec:update}); "
        r"they are not part of the tallies above. \emph{Set}: P dated 2--8~October; L dated in the main window but "
        r"retrieved only by the update search; R Zenodo record dated in the main window and re-screened. Codes were "
        r"double-coded blind and disagreements adjudicated; rationales are in "
        r"\texttt{data/evidence\_coding\_update\_2026-10-08.csv}.",
        "",
        r"\begin{longtable}{@{}p{0.07\linewidth}p{0.26\linewidth}p{0.05\linewidth}p{0.07\linewidth}p{0.16\linewidth}p{0.09\linewidth}p{0.12\linewidth}@{}}",
        r"\caption{Coded evidence from the update search, by requirement.}\label{tab:evidence-update}\\",
        uhead + r" \endfirsthead",
        uhead + r" \endhead",
        r"\bottomrule \endfoot",
    ]
    for r in upd:
        mark = r"\zmark{}" if r["source"] == "zenodo" else ""
        lines.append(f"{r['axis']} & \\cite{{{r['doc']}}}{mark} & {setmark[r['set']]} & {r['code']} & "
                     f"{COMP.get(r['comparator'], r['comparator'])} & {SYSTEM.get(r['system'], r['system'])} & {r['quality']} \\\\")
    lines += [r"\end{longtable}", r"\endgroup", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"{len(tallied)} rows; {len(other)} untallied documents; {len(upd)} update rows -> {OUT}")


if __name__ == "__main__":
    main()
