"""Generate paper/corpus.bib from data/papers.csv (grey literature lives in grey.bib, verified by hand).

Keys: arXiv papers -> arx<5 digits> (e.g. arx29429 for P-29429), alphaXiv -> alphaRAG.
Run: python paper/gen_corpus_bib.py
"""
import csv
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = Path(__file__).resolve().parent / "corpus.bib"
URLDATE = "2026-10-01"


def tex(s):
    s = s.replace("\\", "").replace("&", r"\&").replace("%", r"\%").replace("_", r"\_").replace("#", r"\#")
    s = s.replace("''", '"').replace('``', '"')
    s = re.sub(r'"([^"]*)"', r"``\1''", s)
    return s


def key_for(row):
    if row["arxiv_id"]:
        return "arx" + row["arxiv_id"].split(".")[1]
    return "alpha" + row["id"].split("-", 1)[1]


def full_version(r):
    """Versioned arXiv id; metadata rows store either '2609.12345v1' or just 'v1'."""
    v = r["version"]
    return v if v.startswith(r["arxiv_id"]) else r["arxiv_id"] + v


def main():
    entries = []
    for r in csv.DictReader((ROOT / "data" / "papers.csv").open(encoding="utf-8")):
        authors = " and ".join(a.strip() for a in r["authors"].split(";"))
        if r["arxiv_id"]:
            entries.append(
                f"@misc{{{key_for(r)},\n"
                f"  title = {{{{{tex(r['title'])}}}}},\n"
                f"  author = {{{tex(authors)}}},\n"
                f"  year = {{2026}},\n"
                f"  eprint = {{{r['arxiv_id']}}},\n"
                f"  archivePrefix = {{arXiv}},\n"
                f"  primaryClass = {{{r['primary_category']}}},\n"
                f"  note = {{arXiv:{full_version(r)}, first submitted {r['published']}}},\n"
                f"  url = {{https://arxiv.org/abs/{full_version(r)}}}\n}}\n")
        else:
            entries.append(
                f"@misc{{{key_for(r)},\n"
                f"  title = {{{{{tex(r['title'])}}}}},\n"
                f"  author = {{{tex(authors)}}},\n"
                f"  year = {{2026}},\n"
                f"  howpublished = {{alphaXiv preprint, {r['published']}}},\n"
                f"  url = {{{r['url']}}},\n"
                f"  urldate = {{{URLDATE}}}\n}}\n")
    for z in csv.DictReader((ROOT / "data" / "zenodo_preprints.csv").open(encoding="utf-8")):
        authors = " and ".join("{" + a.strip() + "}" if " " not in a.strip() else a.strip()
                               for a in z["authors"].split(";"))
        entries.append(
            f"@misc{{zen{z['doi'].rsplit('.', 1)[1]},\n"
            f"  title = {{{{{tex(z['title'])}}}}},\n"
            f"  author = {{{tex(authors)}}},\n"
            f"  year = {{2026}},\n"
            f"  howpublished = {{Zenodo {z['type']}, {z['date']}}},\n"
            f"  doi = {{{z['doi']}}},\n"
            f"  url = {{https://doi.org/{z['doi']}}}\n}}\n")
    OUT.write_text("% Generated by gen_corpus_bib.py from data/*.csv; do not edit by hand.\n\n"
                   + "\n".join(entries), encoding="utf-8")
    print(f"{len(entries)} entries -> {OUT}")


if __name__ == "__main__":
    main()
