"""Generate sections/C_catalogue.tex (Appendix C) from data/papers.csv and data/zenodo_preprints.csv.

MODEL records which system each arXiv/alphaXiv study actually measured, from the full-text notes:
H = hosted Jev (TypeSafe), O = open-weight or other typed model only, H+O = both, - = no typed model measured.
Run: python paper/gen_catalogue.py
"""
import csv
from pathlib import Path

from gen_corpus_bib import key_for, tex

ROOT = Path(__file__).resolve().parents[1]
OUT = Path(__file__).resolve().parent / "sections" / "C_catalogue.tex"
TIER_EN = {"核心": "Core", "相关": "Related", "背景": "Background"}

MODEL = {
    # version 0.1 corpus
    "2609.29429": "H", "2609.34862": "H", "2609.28613": "H", "2609.30243": "H+O", "2609.26758": "H+O",
    "2609.24574": "H+O", "2609.35342": "H+O", "2609.33209": "H", "2609.24052": "H", "2609.24965": "H",
    "2609.27678": "H", "2609.32160": "H+O", "2609.26550": "H", "2609.29769": "H", "2609.26532": "H",
    "2609.27607": "H", "2609.23959": "O", "2609.22664": "-", "2609.28940": "H+O", "2609.35293": "H",
    "2609.27535": "H", "2609.28919": "H", "2609.30216": "H", "2609.24881": "H", "2609.22753": "H+O",
    "2609.23136": "H", "2609.23886": "H+O", "2609.23986": "H", "2609.24395": "H", "2609.25498": "O",
    "2609.25845": "O", "2609.27331": "H", "2609.28587": "H", "2609.29283": "O", "2609.30186": "H",
    "2609.34180": "H", "": "H",
    # added in version 0.2
    "2609.31142": "H", "2609.33401": "H+O", "2609.33671": "O", "2609.33843": "O", "2609.33971": "H+O",
    "2609.34024": "H", "2609.37470": "H+O", "2609.37647": "H", "2609.38827": "H+O", "2609.38850": "O",
    "2609.35286": "H", "2609.36399": "H", "2609.36965": "H+O", "2609.33689": "H+O", "2609.34963": "H",
    "2609.30706": "O", "2609.35865": "O", "2609.33282": "O",
    "2609.30922": "H", "2609.33538": "H+O", "2609.33874": "H+O", "2609.34227": "H", "2609.34261": "H",
    "2609.34969": "H", "2609.36059": "H", "2609.36115": "H+O", "2609.36116": "H+O", "2609.36154": "H",
    "2609.39111": "H+O",
    # added in version 0.3 (from the system field of data/evidence_coding.csv)
    "2610.00213": "H", "2610.00346": "H+O", "2609.40241": "H", "2610.00437": "H+O", "2609.39496": "H",
    "2610.00381": "O", "2610.00376": "H", "2610.00831": "O", "2610.02076": "O", "2610.02048": "H",
    "2610.01834": "H", "2610.01231": "-", "2610.01079": "H", "2610.01006": "H", "2610.02046": "H",
}
# read in full and then treated as context, not counted (see scripts/merge_coding.py)
EXCLUDED = {"2609.22664", "zen22953637"}

HEAD = r"\toprule Ref. & Title & First sub. & Tier & Req. & Model \\ \midrule"
ZHEAD = r"\toprule Ref. & Title & Date & Type & Req. \\ \midrule"


def main():
    rows = list(csv.DictReader((ROOT / "data" / "papers.csv").open(encoding="utf-8")))
    # requirements per document from the released coding (rows that enter the tallies)
    req = {}
    for e in csv.DictReader((ROOT / "data" / "evidence_coding.csv").open(encoding="utf-8")):
        if e["in_tally"] == "yes":
            req.setdefault(e["doc"], set()).add(e["axis"])

    def reqs(key):
        return " ".join(sorted(req.get(key, []))) or "--"
    zen = list(csv.DictReader((ROOT / "data" / "zenodo_preprints.csv").open(encoding="utf-8")))
    missing = [r["arxiv_id"] for r in rows if r["arxiv_id"] not in MODEL]
    if missing:
        raise SystemExit(f"MODEL entry missing for {missing}")
    order = {"核心": 0, "相关": 1, "背景": 2}
    rows.sort(key=lambda r: (order[r["tier"]], reqs(key_for(r)).replace("--", "G9"), r["published"]))
    zen.sort(key=lambda z: (reqs("zen" + z["doi"].rsplit(".", 1)[1]).replace("--", "G9"), z["date"]))
    lines = [
        "% Generated by gen_catalogue.py from data/papers.csv and data/zenodo_preprints.csv; do not edit by hand.",
        r"\section{Catalogue of studies}",
        r"\label{app:catalogue}",
        "",
        r"\Cref{tab:catalogue} lists the arXiv and alphaXiv studies in the corpus, and \cref{tab:zenodo} the Zenodo records; all were read in full. "
        r"Entries marked * were read in full and then treated as context because they measure no typed model; they are not counted. "
        r"\emph{Model}: H = hosted \jev{}; O = an open or other typed model only; H+O = both; -- = no typed model measured. \emph{Req.}: requirements for which the study is coded (\cref{app:evidence}). "
        r"Machine-readable metadata, licences and abstracts are in \texttt{data/papers.csv} and \texttt{data/zenodo\_preprints.csv}.",
        "",
        r"\begingroup\scriptsize",
        r"\renewcommand{\arraystretch}{1.15}",
        r"\begin{longtable}{@{}p{0.075\linewidth}p{0.50\linewidth}p{0.065\linewidth}p{0.095\linewidth}p{0.08\linewidth}p{0.045\linewidth}@{}}",
        r"\caption{arXiv and alphaXiv studies, by tier and requirement.}\label{tab:catalogue}\\",
        HEAD + r" \endfirsthead",
        HEAD + r" \endhead",
        r"\bottomrule \endfoot",
    ]
    for r in rows:
        m = MODEL[r["arxiv_id"]]
        m = "--" if m == "-" else m
        star = "*" if r["arxiv_id"] in EXCLUDED else ""
        lines.append(f"\\cite{{{key_for(r)}}}{star} & {tex(r['title'])} &{r['published'][5:]} & "
                     f"{TIER_EN[r['tier']]} & {reqs(key_for(r))} & {m} \\\\")
    lines += [r"\end{longtable}", ""]
    lines += [
        r"\begin{longtable}{@{}p{0.10\linewidth}p{0.52\linewidth}p{0.07\linewidth}p{0.11\linewidth}p{0.08\linewidth}@{}}",
        r"\caption{Zenodo records (preprints, notes, datasets and essays).}\label{tab:zenodo}\\",
        ZHEAD + r" \endfirsthead",
        ZHEAD + r" \endhead",
        r"\bottomrule \endfoot",
    ]
    for z in zen:
        key = "zen" + z["doi"].rsplit(".", 1)[1]
        star = "*" if key in EXCLUDED else ""
        lines.append(f"\\cite{{{key}}}{star} & {tex(z['title'])} & {z['date'][5:]} & {tex(z['type'])} & {reqs(key)} \\\\")
    lines += [r"\end{longtable}", ""]

    # update search of 2026-10-08: every source read in full, with its tier
    import re
    bib = (Path(__file__).resolve().parent / "corpus_update.bib").read_text(encoding="utf-8")
    meta = {}
    for m in re.finditer(r"@misc\{(\w+),\n  title = \{\{(.*?)\}\},.*?(?:first submitted|Zenodo [^,]*,) (\d{4}-\d{2}-\d{2})", bib, re.S):
        meta[m.group(1)] = (m.group(2), m.group(3))
    ucode = list(csv.DictReader((ROOT / "data" / "evidence_coding_update_2026-10-08.csv").open(encoding="utf-8")))
    ureq, uset, nonemp = {}, {}, set()
    for e in ucode:
        uset[e["doc"]] = e["set"]
        if e["in_tally"] == "yes":
            ureq.setdefault(e["doc"], set()).add(e["axis"])
        elif e["empirical"] != "yes":
            nonemp.add(e["doc"])
    udocs = [q["doc"] for q in csv.DictReader((ROOT / "data" / "quality_appraisal_update_2026-10-08.csv").open(encoding="utf-8"))]
    setmark = {"post-window": "P", "late-indexed": "L", "re-screened": "R"}

    # read in full, but contains no evaluation of a typed model (paper/review/coding/docs_update_Z2.md)
    no_eval = {"zen23187206"}
    # non-empirical records that have no coding rows (paper/review/coding/docs_update_Z2.md)
    nonemp |= {"zen23138396"}

    def tier(d):
        if d in no_eval:
            return "Excluded"
        if d in ureq:
            return "Coded"
        return "Non-emp." if d in nonemp else "Context"
    udocs.sort(key=lambda d: ({"Coded": 0, "Context": 1, "Non-emp.": 2, "Excluded": 3}[tier(d)], d))
    UHEAD = r"\toprule Ref. & Title & Date & Set & Tier & Req. \\ \midrule"
    lines += [
        r"\Cref{tab:catalogue-update} lists the 57 sources retained after full-text reading in the update search of 8~October (\cref{sec:update}). "
        r"\emph{Set}: P dated 2--8~October; L dated in the main window but retrieved only by this search; R Zenodo record dated "
        r"in the main window and re-screened; a dash where no row was coded. Metadata are in \texttt{paper/corpus\_update.bib}.",
        "",
        r"\begin{longtable}{@{}p{0.10\linewidth}p{0.50\linewidth}p{0.065\linewidth}p{0.04\linewidth}p{0.08\linewidth}p{0.10\linewidth}@{}}",
        r"\caption{Sources retained after full-text reading in the update search.}\label{tab:catalogue-update}\\",
        UHEAD + r" \endfirsthead",
        UHEAD + r" \endhead",
        r"\bottomrule \endfoot",
    ]
    for d in udocs:
        title, date = meta.get(d, ("", ""))
        mark = r"\zmark{}" if d.startswith("zen") else ""
        lines.append(f"\\cite{{{d}}}{mark} & {title} & {date[5:]} & {setmark.get(uset.get(d, ''), '--')} & {tier(d)} & "
                     f"{' '.join(sorted(ureq.get(d, []))) or '--'} \\\\")
    lines += [r"\end{longtable}", r"\endgroup", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"{len(rows)} papers + {len(zen)} Zenodo rows -> {OUT}")


if __name__ == "__main__":
    main()
